name: dev-story
description: "Execute a story by implementing tasks/subtasks, writing tests, validating, and updating the story file per acceptance criteria"
author: "BMad"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
story_dir: "{config_source}:implementation_artifacts"
date: system-generated

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/dev-story"
instructions: "{installed_path}/instructions.xml"
validation: "{installed_path}/checklist.md"

story_file: "" # Explicit story path; auto-discovered if empty
implementation_artifacts: "{config_source}:implementation_artifacts"
sprint_status: "{implementation_artifacts}/sprint-status.yaml"
project_context: "**/project-context.md"

# --- Secture Mode Awareness ---
# Before executing this workflow, the Dev agent MUST have completed the Secture
# Adaptation protocol (VERIFY / REFINE / GENERATE).
# - VERIFY mode: Validate that the story's tasks, subtasks, and tests are correct
#   and aligned with specifications. Do NOT regenerate code or tests.
# - REFINE mode: Improve existing implementation — fix failing tests, add missing
#   coverage, or adjust code to match updated acceptance criteria. Preserve valid work.
# - GENERATE mode: Execute as originally designed — implement story from scratch.
