name: manage-pr
description: "Create, review status, or merge pull requests via GitHub MCP"
author: "BMad"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
project_name: "{config_source}:project_name"
date: system-generated

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/git/manage-pr"
steps_path: "{installed_path}/steps"

# MCP dependency
required_mcps:
  - name: "GitHub MCP Server"
    check: "Attempt to list pull requests via MCP"
    fallback: "Redirect user to Smithers (SM) for setup"

# --- Secture Mode Awareness ---
# VERIFY: List open PRs and their status.
# REFINE: Update existing PR (add reviewers, update description, resolve conflicts).
# GENERATE: Create a new PR from a feature branch.
